<?php
if (!defined('INCLUDED') || INCLUDED !== true) {
    exit;
}

header('Content-Type: text/plain; charset=UTF-8');

$realmId = isset($_GET['realm']) ? (int)$_GET['realm'] : 1;
$host = '';

require_once(__DIR__ . '/../../config/config-protected.php');

if (!empty($clientConnectionHost)) {
    $host = trim((string)$clientConnectionHost);
}

if ($host === '' && !empty($_SERVER['HTTP_HOST'])) {
    $host = preg_replace('/:\d+$/', '', (string)$_SERVER['HTTP_HOST']);
}

if ($host === '' && function_exists('spp_get_pdo')) {
    try {
        $pdo = spp_get_pdo('realmd', $realmId);
        $stmt = $pdo->prepare('SELECT `address` FROM `realmlist` WHERE `id` = ? LIMIT 1');
        $stmt->execute(array($realmId));
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if (!empty($row['address'])) {
            $host = (string)$row['address'];
        }
    } catch (Throwable $e) {
        // Fall back below.
    }
}

if ($host === '') {
    $host = (string)($_SERVER['SERVER_ADDR'] ?? '127.0.0.1');
}

$safeRealmId = max(1, $realmId);
$filename = ($safeRealmId === 1) ? 'realmlist.wtf' : ('realmlist-' . $safeRealmId . '.wtf');
header('Content-Disposition: attachment; filename="' . $filename . '"');

echo '# autogenerated by website' . "\r\n";
echo 'set realmlist ' . $host . "\r\n";
exit;
?>
